/*
   Sábado, 05 de Septiembre de 2009 08:37:50 a.m.
   Usuario: 
   Servidor: JUAN\SQL2000
   Base de datos: SistemaContableMarAzul
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.DetalleProrrateo ADD CONSTRAINT
	FK_DetalleProrrateo_Prorrateo FOREIGN KEY
	(
	NumeroProrrateo
	) REFERENCES dbo.Prorrateo
	(
	NumeroProrrateo
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	
GO
COMMIT
