/*
   Sábado, 19 de Diciembre de 2009 11:44:09 a.m.
   Usuario: 
   Servidor: JUAN\SQL2000
   Base de datos: SistemaContablePedrera
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.Cuentas ADD
	CodCuentaImporta nvarchar(50) NULL
GO
COMMIT
