/*
   domingo, 23 de agosto de 2009 22:52:42
   Usuario: 
   Servidor: JUAN\SQL2000
   Base de datos: SistemaContableCorredora
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.Cuentas ADD CONSTRAINT
	DF_Cuentas_CausaIva DEFAULT 0 FOR CausaIva
GO
ALTER TABLE dbo.Cuentas ADD CONSTRAINT
	DF_Cuentas_CausaRetencion DEFAULT 0 FOR CausaRetencion
GO
COMMIT
