/*
   Sábado, 29 de Agosto de 2009 03:04:46 p.m.
   Usuario: 
   Servidor: JUAN\SQL2000
   Base de datos: SistemaContableMarAzul
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.Transacciones ADD CONSTRAINT
	DF_Transacciones_CodCuentaProveedor DEFAULT 0 FOR CodCuentaProveedor
GO
ALTER TABLE dbo.Transacciones ADD CONSTRAINT
	DF_Transacciones_TipoFactura DEFAULT N'-' FOR TipoFactura
GO
COMMIT
